/*
 * dsp.h
 * =====
 *
 * Digital Signal Processing (DSP) module
 * - Demodulates IQ baseband samples for AM, USB, LSB, CW and FM modes
 * - Applies IIR audio filter with three selectable bandwidths per mode
 * - Rx frontend Automatic Gain Control (AGC) via DA0 output voltage
 *
 * Signal chain (per sample, called from S12AD0 A/D interrupt):
 * 1. Removes DC bias using dynamic IIR tracker (measured_dc_i/q)
 *	- Bias is set using a voltage divider across 5V rail, which is unregulated so the DC bias can't be fixed in firmware
 * 2. Amplifies signal by fixed digital gain (DIGITAL_GAIN)
 * 3. Demodulates the signal according to selected mode
 * 4. Applies IIR audio filter according to selected filter width (see lookup table in dsp.cpp for exact values)
 * 5. Detects peak of demodulated signal and updates Automatic Gain Control (AGC) control voltage in response
 *
 * AGC voltage range:
 * - AGC_MIN_VOLTAGE: minimum gain (strong signal)
 * - AGC_MAX_VOLTAGE: maximum gain (weak signal / no signal)
 * - AGC_TARGET: peak audio level the AGC aims to maintain
 *
 * FFT buffers (fft_i/fft_q) are filled in the ISR and processed in the main program loop when fft_ready is set.
 *
 * C/C++ compatibility:
 * - S12AD0 interupt handler generated by Smart Configurator is in C (Config_S12AD0_user.c)
 * - Therefore, dsp_process() is exposed as extern "C" for calling from C ISR
 * - DSP class definition is guarded by __cplusplus for C compatibility
 * - Measured_dc_i/q are defined in Config_S12AD0_user.c and shared between the ISR and DSP class via extern declarations
 */
 
#ifndef dsp_h
#define dsp_h

#include <stdint.h>

#define AM                  0
#define USB                 1
#define LSB                 2
#define CW                  3
#define FM                  4

// AGC
// AGC CV drives MOSFETs which control the RX gain - these are highly non-linear, which should be accounted for!
#define AGC_TARGET          100         
#define AGC_INITIAL_VOLTAGE 2450	// 3.5V / 14dB
#define AGC_MAX_VOLTAGE     2950  	// 4.02V / 44dB
#define AGC_MIN_VOLTAGE     2000  	// 2.99V / 0dB
#define AGC_ATTACK          1
#define AGC_DECAY           5

#define DIGITAL_GAIN        2

#define FFT_SIZE            128
#define FFT_LOG2            7

// Q amplitude is smaller than I due to quadrature divider circuit
#define Q_GAIN_CORRECTION  2	

extern volatile int8_t fft_real[FFT_SIZE];
extern volatile int8_t fft_imag[FFT_SIZE];
extern volatile uint8_t fft_ready;

// Define class structure if header referenced by C code.
#ifdef __cplusplus
class DSP {
    public:
        void init();
        void update();
        void set_mode(signed char);
        uint8_t get_mode();
        char * get_mode_string();
        void set_filter_width(signed char);
        uint8_t get_filter_width();
        char * get_filter_width_string();
        uint16_t get_filter_width_hz();
        uint16_t process(uint16_t i_raw, uint16_t q_raw);
        uint16_t get_agc_voltage();

    private:
        uint8_t mode;
        uint8_t filter_width;
        uint16_t agc_voltage;

        // Persitent filter states across samples
        int32_t filter_state;
        int32_t fm_i_prev;
        int32_t fm_q_prev;

        // AGC state
        uint16_t agc_peak;
        uint32_t agc_counter;

        // DSP methods
        int32_t apply_filter(int32_t input, uint8_t mode, uint8_t width);
	uint16_t noise_reduce(uint16_t input);
        int32_t process_am(int32_t i, int32_t q);
        int32_t process_usb(int32_t i, int32_t q);
        int32_t process_lsb(int32_t i, int32_t q);
        int32_t process_cw(int32_t i, int32_t q);
        int32_t process_fm(int32_t i, int32_t q);
};

#endif // __cplusplus

// C and C++ compatible declartions
extern volatile int16_t measured_dc_i;
extern volatile int16_t measured_dc_q;

// C compatible wrapper for DSP processing - called from A/D interrupt
#ifdef __cplusplus
extern "C" {
#endif
uint16_t dsp_process(uint16_t i_raw, uint16_t q_raw);

#ifdef __cplusplus
}
#endif

#endif // dsp_h
